version: "3.9"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/gis_starter_postgis_geolab:cached
    depends_on:
      - postgis
    environment:
      - PGHOST=postgis
      - PGUSER=gisuser
      - PGPASSWORD=gispass
      - PGDATABASE=gisdb
      - PGPORT=5432

  postgis:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "Lax"
      PGADMIN_CONFIG_SESSION_COOKIE_SECURE: "False"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "1"
    ports:
      - "5050:80"
    depends_on:
      - postgis
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
