version: "3.9"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/gis_starter_postgis_geolab:cached
    depends_on:
      - postgis
    environment:
      - PGHOST=postgis
      - PGUSER=gisuser
      - PGPASSWORD=gispass
      - PGDATABASE=gisdb
      - PGPORT=5432

  postgis:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_CSRF_ENABLED=False
      - PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE=None
      - PGADMIN_CONFIG_SESSION_COOKIE_SECURE=True
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PORT_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
    ports:
      - "5050:5050"
    depends_on:
      - postgis
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - pgadmin

volumes:
  postgres_data:
  pgadmin_data: