version: "3.9"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/gis_starter_postgis_geolab:cached
    depends_on:
      - postgis
    environment:
      - PGHOST=postgis
      - PGUSER=gisuser
      - PGPASSWORD=gispass
      - PGDATABASE=gisdb
      - PGPORT=5432

  postgis:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispass
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
